os: osx
cache:
  directories:
    - bower_components
    - node_modules
    - app/node_modules
before_install:
    - brew update
    - brew cask install google-chrome
    - npm install grunt-cli -g
    - npm install
install:
    - grunt dev
script:
    - npm test
before_deploy:
    - travis/build.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - release/chrome/chrome-app.zip
    - release/electron/darwin-x64.zip
  on:
    all_branches: true
    tags: true
