sudo: required
dist: trusty
language: objective-c
cache:
  directories:
    - node_modules
env:
    - NODE_VERSION="6.1"
before_install:
    - npm install grunt-cli -g
    - npm install
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - grunt dev
script:
    - karma start --single-run
before_deploy:
    - brew update
    - brew install wine
    - wine --version
    - brew install makensis
    - ./build.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - release/chrome/chrome-app.zip
    - release/electron/darwin-x64.zip
    - release/electron/win32-ia32.zip
    - release/electron/win32-x64.zip
  on:
    all_branches: true
    tags: true
