matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      dist: trusty
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  directories:
    - bower_components
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
addons:
  apt:
    packages:
      - icnsutils
before_install:
  - ./scripts/install_chrome.sh
  - npm install grunt-cli -g
  - npm install
install:
  - grunt dev
script:
  - npm test
before_deploy:
  - npm run dist:chrome
  - npm run release
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file:
    - release/chrome/chrome-app.zip
  on:
    all_branches: true
    tags: true
