os: osx
cache:
  directories:
    - bower_components
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
before_install:
    - brew update
    - brew cask install google-chrome
    - npm install grunt-cli -g
    - npm install
install:
    - grunt dev
script:
    - npm test
before_deploy:
    - npm run release
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - release/chrome/chrome-app.zip
  on:
    all_branches: true
    tags: true
