matrix:
  include:
    - os: osx
      addons:
        chrome: beta
    - os: linux
      dist: trusty
      addons:
        - chrome: stable

language: c

cache:
  directories:
    - bower_components
    - node_modules
    - yarn
    - $HOME/.electron

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - npm install yarn -g
  - yarn global add grunt-cli
  - yarn install --ignore-engines

install:
  - grunt dev

script:
  - yarn test

before_deploy:
  - yarn run dist:chrome
  - yarn run dist:electron

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  draft: true
  file:
    - release/chrome/chrome-app.zip
  on:
    all_branches: true
    tags: true

