platform:
  - x64

cache:
  - bower_components
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - choco install googlechrome
  - ps: Install-Product node 8 x64
  - yarn global add grunt-cli
  - yarn

build_script:
  - grunt dev
  - yarn run dist:electron

test_script:
  - yarn test

artifacts:
  - path: release\electron\*.exe,release\electron\latest.yml

