platform:
  - x64

cache:
  - bower_components
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - choco install googlechrome
  - ps: Install-Product node 8 x64
  - yarn global add grunt-cli
  - yarn

build_script:
  - grunt dev
  - yarn run dist:electron

test_script:
  - yarn test

artifacts:
  - path: release\electron\*.exe,latest.yml

deploy:
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: v5qEZPfyCd2WwTjoIKRfotA4atyU6PSPEztHcs3FTkr07WnGHNFOT0NA82aqVjWq
  artifact: release\electron\*.exe,latest.yml
  on:
    branch: master
    appveyor_repo_tag: true

