version: '1.0.{build}'
os: unstable
platform:
  - x86
  - x64
matrix:
  fast_finish: true
shallow_clone: true
clone_depth: 1
cache:
  - bower_components
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
environment:
  matrix:
    - nodejs_version: 6
install:
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g grunt-cli
  - npm install
build_script:
  - grunt dev
  - npm run dist:electron
test_script:
  - npm test
artifacts:
  - path: release\electron\*.exe
