version: '1.0.{build}'
os: unstable
cache:
  - bower_components
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
environment:
  matrix:
    - nodejs_version: 6
install:
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g grunt-cli
  - npm install
matrix:
  fast_finish: true
build_script:
  - npm run release
shallow_clone: true
clone_depth: 1
test_script:
  - npm test
artifacts:
  - path: release\electron\*.exe
deploy:
  - provider: GitHub
    auth_token:
      secure: +rD8EayrPxpJ4TLIwPupv+M+dHEQuf1MgdGFdQSXz0SUFpDUxCmm34Vw1sFLNjBl
    on:
      appveyor_repo_tag: true
