version: '1.0.{build}'

platform:
  - x64

cache:
  - bower_components
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - choco install googlechrome
  - ps: Install-Product node 6 x64
  - npm install -g npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g grunt-cli
  - npm install

build_script:
  - grunt dev
  - npm run dist:electron

test_script:
  - npm test

artifacts:
  - path: release\electron\*.exe
