version: '1.0.{build}'

platform:
  - x64

cache:
  - bower_components
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - choco install googlechrome
  - ps: Install-Product node 6 x64
  - npm install -g yarn grunt-cli
  - set PATH=%APPDATA%\yarn;%PATH%
  - yarn install

build_script:
  - grunt dev
  - yarn run dist:electron

test_script:
  - yarn test

artifacts:
  - path: release\electron\*.exe
