version: '1.0.{build}'
os: unstable
cache:
  - bower_components
  - node_modules
  - app/node_modules
environment:
  matrix:
    - nodejs_version: 6
artifacts:
  - path: release\electron\*.zip
    name: RedmineTimeTrackerInstaller
    type: zip
install:
  - choco install googlechrome
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g grunt-cli
  - npm install
matrix:
  fast_finish: true
build_script:
  - grunt dev
  - grunt build-electron
shallow_clone: true
clone_depth: 1
test_script:
  - npm test
before_deploy:
  - npm run clean
  - npm run build:win32
  - npm run build:win64
  - grunt compress:win32
  - grunt compress:win64
deploy:
  - provider: GitHub
    auth_token:
      secure: +rD8EayrPxpJ4TLIwPupv+M+dHEQuf1MgdGFdQSXz0SUFpDUxCmm34Vw1sFLNjBl
    artifact: /.*\.zip/
    on:
      appveyor_repo_tag: true
